# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d804da3d357a7aaaa23d52fa70efbad558b5e6e4960a8fee03c04537cbe557a99e489b4e6b3409fc35142789f15838fe4405ce31b76f201996314b53f225867

test:
  secret_key_base: fea7b77a6128b63abb300da6b9eb5aa2f94fe0ca5a7088e584756c0dc0a25139bcba8d9add64f81cf1327ffe616b534337db57c92f9c2164710bc6476b45e57f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
